# Generated by Django 3.1 on 2020-08-15 16:15

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=80)),
                ('second_name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
    ]
